# Tourism Dataset Exploratory Data Analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggcorrplot)
library(RColorBrewer)
library(gridExtra)
```

```{r, message=FALSE, warning=FALSE}
tourism_df <- read.csv("../data/processed/full_tourism_dataset.csv")

tourism_df <- tourism_df %>% 
  filter(year < 2020) %>% 
  filter(total_inbound_tourism_expenditure >= 0 | total_arrivals >= 0) %>% 
  mutate(world_region = as.factor(world_region),
         hdi_code = as.factor(hdi_code))

tourism_df <- tourism_df %>% 
  mutate(tourism_grew = as.factor(ifelse(inbound_tourism_expenditure_growth >= 0.05, "Y", "N"))) %>% 
  mutate(log_gdp = log(gdp),
         log_gdp_per_capita = log(gdp_per_capita),
         log_total_inbound_tourism_expenditure = log(total_inbound_tourism_expenditure))
```

```{r}
col_grid <- rgb(235, 235, 235, 100, maxColorValue = 255)
```

## Hotel Guests Over Time

```{r, message=FALSE, warning=FALSE}
ggplot(tourism_df, aes(x = year, y = hotel_guests*1000)) +
  
  stat_summary(fun.y = "sum", 
               geom = "bar", 
               position = "identity",
               fill = "seagreen4",
               color = "black",
               width = 1) +
  
  scale_y_continuous(labels = scales::unit_format(unit = "M", scale = 1e-6, big.mark = ",")) +
  
  scale_x_continuous(limits = c(1994,2020), 
                     breaks = c(seq(1995,2015,by = 5),2019)) +
  
  labs(x = "Year", 
       y = "Hotel Guests", 
       title = "Total Hotel Guests by Year (1995 - 2019)") +
  
  theme_bw() +
  
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold.italic"))
```

## Tourism Income by Region

```{r}
positions <- rev(c("Europe and Central Asia","East Asia and Pacific","North America","Middle East and North Africa","Latin America and the Caribbean", "South Asia", "Sub-Saharan Africa"))

ggplot(filter(tourism_df, year == 2019), aes(x = world_region, y = total_inbound_tourism_expenditure, fill = world_region)) +
  geom_bar(stat = "summary", fun = "sum", color = "black", width = 1) +
  geom_text(stat = "summary", 
            fun = "sum", 
            aes(label = paste0("italic('$", round(after_stat(y)/1000, 1), "B')")),
            position = position_dodge(width= 1), 
            hjust = -0.05,
            size = 4.3,
            parse = T
            ) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 500000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_discrete(limits = positions) +
  scale_fill_brewer(palette = "YlGnBu") +
  labs(y = "Total Inbound Tourism Expenditure (in USD)", 
       x = "World Region",
       title = "2019 Tourism Income by World Region") +
  theme_bw() +
  theme(legend.position = "none") +
  theme(panel.grid = element_line(color = col_grid)) +
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold.italic"))
```

## Top 20 Countries Tourism Income and HDI Status

```{r fig.width=7, fig.height=5} 
tourism_2019_top_20 <- tourism_df %>% 
  filter(year == 2019) %>%
  mutate(hdi_code = ifelse(is.na(hdi_code), "N/A", hdi_code) ) %>% 
  group_by(country, hdi_code) %>% 
  summarise(country_sum = sum(total_inbound_tourism_expenditure)) %>% 
  arrange(desc(country_sum)) %>% 
  head(20)

positions <- rev(tourism_2019_top_20$country)

ggplot(tourism_2019_top_20, aes(x = country, y = country_sum, ))+#fill = hdi_code) ) +
  geom_bar(stat = "summary", 
           fun = "sum", 
           aes(fill = hdi_code),
           color = "black", 
           width = 1,
           show.legend = T) +
  geom_text(stat = "summary", 
            fun = "sum", 
            aes(label = paste0("italic('$", round(after_stat(y)/1000, 1), "B')")),
            position = position_dodge(width= 1), 
            hjust = -0.05,
            size = 3,
            parse = T
            ) +
  coord_flip() +
  scale_y_continuous(limits = c(0, 265000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_discrete(limits = positions) +
  scale_fill_manual(values = c(
    "High" = "greenyellow", 
    "Medium" = "gold", 
    "Very High" = "forestgreen", 
    "Low" = "red3"),
    limits = c("Very High","High","Medium","Low",NA),
    breaks = c("Very High","High","Medium","Low",NA)
    ) +
  labs(y = "Total Inbound Tourism Expenditure (in USD)", 
       x = "Country",
       title = "Top 20 Countries in Tourism Income (2019)",
       fill = "HDI Status") +
  theme_bw() +
  theme(panel.grid = element_line(color = col_grid)) +
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold.italic"))
```

## Bottom 20 Countries Tourism Income and HDI Status

```{r fig.width=7, fig.height=5} 
tourism_2019_bottom_20 <- tourism_df %>% 
  filter(year == 2019) %>%
  drop_na(total_inbound_tourism_expenditure) %>%
  group_by(country, hdi_code) %>% 
  summarise(country_sum = sum(total_inbound_tourism_expenditure)) %>% 
  arrange(desc(country_sum)) %>% 
  tail(20)

positions <- (tourism_2019_bottom_20$country)

ggplot(tourism_2019_bottom_20, aes(x = country, y = country_sum, ))+#fill = hdi_code) ) +
  geom_bar(stat = "summary", 
           fun = "sum", 
           aes(fill = hdi_code),
           color = "black", 
           width = 1,
           show.legend = T) +
  geom_text(stat = "summary", 
            fun = "sum", 
            aes(label = paste0("italic('$", round(after_stat(y), 1), "M')")),
            position = position_dodge(width= 1), 
            hjust = -0.05,
            size = 3,
            parse = T
            ) +
  coord_flip() +
  scale_y_continuous(limits = c(0,165), labels = scales::unit_format(unit = "M", scale = 1, big.mark = ",")) +
  scale_x_discrete(limits = positions) +
  scale_fill_manual(values = c(
    "High" = "greenyellow", 
    "Medium" = "gold", 
    "Very High" = "forestgreen", 
    "Low" = "red3"),
    limits = c("Very High","High","Medium","Low",NA),
    breaks = c("Very High","High","Medium","Low",NA)
    ) +
  labs(y = "Total Inbound Tourism Expenditure (in USD)", 
       x = "Country",
       title = "Bottom 20 Countries in Tourism Income (2019)",
       fill = "HDI Status") +
  theme_bw() +
  theme(panel.grid = element_line(color = col_grid)) +
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold.italic"))
```

## Economic Indicators

```{r}
# GDP Per Capita
gpc_cor <- round(cor(tourism_df$gdp_per_capita, tourism_df$total_inbound_tourism_expenditure, use = "pairwise.complete.obs"),4)

ggplot(tourism_df, aes(x = gdp_per_capita, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 95000, y = 240000, size = 8, label = paste("R =",gpc_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,250000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(labels = scales::label_comma()) +
  labs(x = "GDP Per Capita (in USD)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()

ggplot(tourism_df, aes(x = gdp_per_capita, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 95000, y = 72000, size = 8, label = paste("R =",gpc_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,75000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(labels = scales::label_comma()) +
  labs(x = "GDP Per Capita (in USD)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()

# GDP
gdp_cor <- round(cor(tourism_df$gdp, tourism_df$total_inbound_tourism_expenditure, use = "pairwise.complete.obs"),4)

ggplot(tourism_df, aes(x = gdp, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 2500, y = 240000, size = 8, label = paste("R =",gdp_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,250000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(limits = c(0,20000), labels = scales::unit_format(unit = "T", scale = 1e-3, big.mark = ",")) +
  labs(x = "GDP (in 2015 USD)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()

ggplot(tourism_df, aes(x = gdp, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 500, y = 72000, size = 8, label = paste("R =",gdp_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,75000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(limits = c(0,5000), labels = scales::unit_format(unit = "T", scale = 1e-3, big.mark = ",")) +
  labs(x = "GDP (in 2015 USD)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()

# Consumer Price Index
cpi_cor <- round(cor(tourism_df$cpi, tourism_df$total_inbound_tourism_expenditure, use = "pairwise.complete.obs"),4)

ggplot(tourism_df, aes(x = cpi, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 25, y = 240000, size = 8, label = paste("R =",cpi_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,250000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(limits = c(0,200)) +
  labs(x = "Consumer Price Index (Base Year 2015 = 100)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()

ggplot(tourism_df, aes(x = cpi, y = total_inbound_tourism_expenditure)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = F, color = "maroon", size = 1.7) +
  annotate("text", x = 25, y = 72000, size = 8, label = paste("R =",cpi_cor), fontface = "italic") +
  scale_y_continuous(limits = c(0,75000), labels = scales::unit_format(unit = "B", scale = 1e-3, big.mark = ",")) +
  scale_x_continuous(limits = c(0,200)) +
  labs(x = "Consumer Price Index (Base Year 2015 = 100)", y = "Total Inbound Tourism Expenditure (in USD)") +
  theme_bw()
```

```{r} 
tourism_df <- tourism_df %>% 
  mutate(condition = as.factor(
    as.numeric(
      (
        (exchange_rate_growth >= 0.025 & total_arrivals_growth >= 0.025) | 
          (exchange_rate_growth <= -0.025 & total_arrivals_growth <= -0.025)
       )
      )
    )
  )

ggplot(tourism_df, aes(x = exchange_rate_growth, y = total_arrivals_growth, color = condition)) +
  geom_point(size = 2, alpha = 0.5) +
  scale_x_continuous(limits = c(-0.25,0.25), labels = scales::percent_format()) +
  scale_y_continuous(limits = c(-0.5,0.5), labels = scales::percent_format()) +
  scale_color_manual(values = c("1" = "darkred", "0" = "black"),
                    limits = c("1","0"),
                    breaks = "1",
                    label = "Exchange rate and visitors\nboth grow > 2.5% or both grow < -2.5%") +
  labs(x = "Exchange Rate Growth", 
       y = "Total Visitors Growth",
       title = "Exchange Rate Growth and Total Visitors Growth",
       color = "Legend") +
  theme_bw() +
  #theme(legend.position = "none") +
  theme(panel.grid = element_line(color = col_grid)) +
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold.italic")) +
 theme(legend.title = element_text(size=8), legend.text=element_text(size=8))
```

## Correlation Matrix

```{r}
correlation_matrix <- round(cor(tourism_df[,-c(1,2,62)],  use = "pairwise.complete.obs"), 3)

correlation_matrix
```

## Infrastructure Scatterplots

```{r}
ggplot(tourism_df, aes(x=hotel_guests, y=total_inbound_tourism_expenditure, color = world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=visitors_personal, y=total_inbound_tourism_expenditure, color = world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=visitors_business_professional, y=total_inbound_tourism_expenditure, color = world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=total_tourism_employees, y=total_inbound_tourism_expenditure, color=world_region)) + geom_point()
```

```{r}
ggplot(tourism_df, aes(x=rooms, y=total_inbound_tourism_expenditure, color=world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=bed_places, y=total_inbound_tourism_expenditure, color=world_region)) + 
  geom_point() + 
  scale_x_continuous(limits = c(0,50000))+geom_smooth(method = "lm", se=FALSE)
```

```{r}
ggplot(tourism_df, aes(x=establishments, y=total_inbound_tourism_expenditure, color=world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=occupancy_rate_per_bed_place, y=total_inbound_tourism_expenditure, color=world_region)) + 
  geom_point()
```

```{r}
ggplot(tourism_df, aes(x=occupancy_rate_per_room, y=total_inbound_tourism_expenditure, color=world_region)) + 
  geom_point()
```